<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1707488394599' stop='1707488397475'>
    <name>test/UAT_Cognito/AuthService_Delete_User.test.js</name>
    <title>test/UAT_Cognito/AuthService_Delete_User.test.js</title>
    <test-cases>
        <test-case start='1707488394599' status='failed' stop='1707488395560'>
            <name>API Success</name>
            <title>API Success</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"</message>
                <stack-trace>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/UAT_Cognito/AuthService_Delete_User.test.js:20:15)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1707488395560' status='failed' stop='1707488396533'>
            <name>Email already exist</name>
            <title>Email already exist</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"</message>
                <stack-trace>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "User not found for the provided email."
                Received: "Invalid Session"
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/UAT_Cognito/AuthService_Delete_User.test.js:36:15)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1707488396534' status='failed' stop='1707488397469'>
            <name>BAD Request</name>
            <title>BAD Request</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "argument of type 'NoneType' is not iterable"
                Received: "Invalid Session"</message>
                <stack-trace>Error: Error: expect(received).toBe(expected) // Object.is equality
                
                Expected: "argument of type 'NoneType' is not iterable"
                Received: "Invalid Session"
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/UAT_Cognito/AuthService_Delete_User.test.js:53:15)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>