<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1709127884849' stop='1709127893123'>
    <name>test/PRODUCTION_Cognito/AuthService_Login.test.js</name>
    <title>test/PRODUCTION_Cognito/AuthService_Login.test.js</title>
    <test-cases>
        <test-case start='1709127884849' status='failed' stop='1709127886258'>
            <name>API Success</name>
            <title>API Success</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1709127884850' status='undefined'>
                    <name>Values passed:"{\"username\":\"msingh@actiontitleresearch.com\",\"password\":\"Msingh@123\"}"</name>
                    <title>Values passed:"{\"username\":\"msingh@actiontitleresearch.com\",\"password\":\"Msingh@123\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Response is not in valid json format</message>
                <stack-trace>Error: Response is not in valid json format
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/PRODUCTION_Cognito/AuthService_Login.test.js:34:15)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1709127886258' status='passed' stop='1709127887500'>
            <name>username is missing </name>
            <title>username is missing </title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709127886258' status='passed' stop='1709127887499'>
                    <name>Values passed:"{\"username\":\"\",\"password\":\"Msingh@123\"}"</name>
                    <title>Values passed:"{\"username\":\"\",\"password\":\"Msingh@123\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (InvalidParameterException) when calling the InitiateAuth operation: Missing required parameter USERNAME","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709127887500' status='passed' stop='1709127888736'>
            <name>password is missing </name>
            <title>password is missing </title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709127887501' status='passed' stop='1709127888736'>
                    <name>Values passed:"{\"username\":\"msingh@actiontitleresearch.com\",\"password\":\"\"}"</name>
                    <title>Values passed:"{\"username\":\"msingh@actiontitleresearch.com\",\"password\":\"\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (InvalidParameterException) when calling the InitiateAuth operation: Missing required parameter PASSWORD","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709127888737' status='passed' stop='1709127890001'>
            <name>wrong username</name>
            <title>wrong username</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709127888738' status='passed' stop='1709127890001'>
                    <name>Values passed:"{\"username\":\"wsdsdmsingh@actiontitleresearch.comejd\",\"password\":\"Msingh@123\"}"</name>
                    <title>Values passed:"{\"username\":\"wsdsdmsingh@actiontitleresearch.comejd\",\"password\":\"Msingh@123\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709127890001' status='passed' stop='1709127891237'>
            <name>wrong password</name>
            <title>wrong password</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709127890002' status='passed' stop='1709127891237'>
                    <name>Values passed:"{\"username\":\"msingh@actiontitleresearch.com\",\"password\":\"Msingh@123sjfeusfeusgfuw\"}"</name>
                    <title>Values passed:"{\"username\":\"msingh@actiontitleresearch.com\",\"password\":\"Msingh@123sjfeusfeusgfuw\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Incorrect username or password.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709127891237' status='passed' stop='1709127892378'>
            <name>username and password both are incorrect</name>
            <title>username and password both are incorrect</title>
            <labels>
                <label name='testId' value='API Endpoint-/services/invoker/cognito/signin'/>
            </labels>
            <parameters/>
            <steps>
                <step start='1709127891238' status='passed' stop='1709127892378'>
                    <name>Values passed:"{\"username\":\"msingh@actiontitleresearch.comsfdbfdbvd\",\"password\":\"Msingh@123sjfeusfeusgfuw\"}"</name>
                    <title>Values passed:"{\"username\":\"msingh@actiontitleresearch.comsfdbfdbvd\",\"password\":\"Msingh@123sjfeusfeusgfuw\"}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <description type='text'>Response message from API:{"body":"An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.","statusCode":500,"headers":{"Content-Type":"application/json"}}</description>
        </test-case>
        <test-case start='1709127892378' status='failed' stop='1709127893110'>
            <name>Plain text received as response</name>
            <title>Plain text received as response</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1709127892379' status='undefined'>
                    <name>Values passed:"{}"</name>
                    <title>Values passed:"{}"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Response is not in valid json format</message>
                <stack-trace>Error: Response is not in valid json format
                    at Object.&lt;anonymous> (/home/devtrust/Project/QA-API-Automation-Testing/test/PRODUCTION_Cognito/AuthService_Login.test.js:156:15)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>